name: Uithoorn Checker
on:
  schedule:
    - cron: "0 7 * * 5"  # UTCで金曜07:00（NL夏時間なら09:00相当）
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -U pip
          pip install selenium webdriver-manager requests pytz
      - name: Run checker
        env:                              # ← Secrets を渡す
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python uithoorn_checker.py
