name: Check Gym Court Availability

on:
  schedule:
    - cron: '0 18 * * 1' # Every Monday at 20:00 NL time (18:00 UTC)
    - cron: '0 18 * * 4' # Every Thursday at 20:00 NL time (18:00 UTC)
    - cron: '0 15 * * 6' # Every Saturday at 17:00 NL time (15:00 UTC)
    - cron: '0 12 * * 0' # Every Sunday at 14:00 NL time (12:00 UTC)
    - cron: '0 13 * * 0' # Every Sunday at 15:30 NL time (13:30 UTC)
  workflow_dispatch:

jobs:
  check-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests pytz

      - name: Run the script
        run: python uithoorn_checker.py
